# Generated by Django 2.1.4 on 2019-02-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiyApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='imgPath',
        ),
        migrations.RemoveField(
            model_name='team',
            name='imgPath',
        ),
    ]
