# Generated by Django 2.1.4 on 2019-02-21 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiyApp', '0002_auto_20190212_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='tournament',
            field=models.ForeignKey(default=2040, null=True, on_delete=django.db.models.deletion.CASCADE, to='SiyApp.Tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='Team',
            field=models.ForeignKey(default=2040, null=True, on_delete=django.db.models.deletion.CASCADE, to='SiyApp.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='imgPath',
            field=models.CharField(default='./Content/imgs/fcb.jpg', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='result',
            name='fixture',
            field=models.ForeignKey(default='1255', null=True, on_delete=django.db.models.deletion.CASCADE, to='SiyApp.Fixture'),
        ),
        migrations.AddField(
            model_name='team',
            name='imgPath',
            field=models.CharField(default='./Content/imgs/fcb.jpg', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(default=2040, null=True, on_delete=django.db.models.deletion.CASCADE, to='SiyApp.Tournament'),
        ),
    ]
