# Generated by Django 2.1.4 on 2019-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiyApp', '0003_auto_20190221_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='imgPath',
            field=models.CharField(default='./Content/imgs/fcb.jpg', max_length=128),
        ),
        migrations.AlterField(
            model_name='team',
            name='imgPath',
            field=models.CharField(default='./Content/imgs/fcb.jpg', max_length=128),
        ),
    ]
